name: "lint and test go"

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Download Go modules
        run: go mod download

      - name: Run format
        run: just format

      - name: Check formatting diff
        run: git diff --exit-code

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Download Go modules
        run: go mod download

      - name: Run lint
        run: just lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Download Go modules
        run: go mod download

      - name: Run tests
        run: just test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          if-no-files-found: error
